### ISSUE TITLE
python pip install without gcc

### ISSUE THREAD

**Issue by UralZima** [edannenberg/gentoo-bb#101]
Hello. I have replaced my stack now with spring-compiled packages. All is fine and working, thanks!

In one my container, I need some extra python modules. I added dev-python/pip to it, and it installed most packages. But some packages (regex) need gcc to compile. I don't want to include gcc to this container, it needed only once. Is there any way to compile package while building container and copy to emerge-root? Regex is available in pip only, I didn't found it on portage
Manually I can copy from /usr/lib/python2.7/site-packages/_some_related_files, but each python package have multiple files and you need to collect them manually

Thanks

**Comment by edannenberg** [comment]
> Is there any way to compile package while building container and copy to emerge-root?

I'm afraid you already know the only two options. Either include gcc in the final image or install via pip in the build container and handle the rest manually. We could add some helpers that could ease the process for the latter I guess, but right now I've got other more pressing issues on my plate. Would have to wait a while unless someone else steps up.

**Comment by azimut** [comment]
There is a pip command to list the files a pip installs. You can use that for the helper. Otherwise you have virtualenvs too.

**Comment by UralZima** [comment]
@azimut, thanks for suggestion, that make life much easier.
