### ISSUE TITLE
Mount portage*.tar.xz to volume instead of copying it

### ISSUE THREAD

**Issue by jbergstroem** [edannenberg/gentoo-bb#108]
We should mount "distfiles" into volumes instead of copying them to the containers; will speed the process up a bit.

**Comment by edannenberg** [comment]
Hm, is this really worth it just for the portage snapshot? Also can you mount a volume now during `docker build`? I feel like I'm missing something obvious. :thinking:

**Comment by jbergstroem** [comment]
@edannenberg doh. of course - not during build.
