### ISSUE TITLE
Create helper for adding use-flags to package from Buildconfig.sh

### ISSUE THREAD

**Issue by jbergstroem** [edannenberg/gentoo-bb#15]
Basically what topic says. Should manage:
 - creating directory structure if it doesn't exist
 - adding use flags
 - possibly checking duplicity and/or overwriting current variables ( for instance USE="foo" would overwrite a previous USE="-foo", not just add to file for readability)

**Comment by steveeJ** [comment]
You may want to check out *app-portage/flaggie* for this purpose.

**Comment by edannenberg** [comment]
@steveeJ thanks for the tip!
