### ISSUE TITLE
Publish to DockerHub

### ISSUE THREAD

**Issue by mcandre** [edannenberg/gentoo-bb#23]
Could you please publish edannenberg/gentoo-bb to [Docker Hub](https://hub.docker.com/) to make it easier for others to use this?

1. Setup a Docker Hub account and repository.
2. `docker push edannenberg/gentoo-bb`

**Comment by edannenberg** [comment]
Images from this repo are pushed monthly to [gentoobb](https://registry.hub.docker.com/repos/gentoobb/?&s=alphabetical) on docker hub. I'm afraid automated docker hub builds are not possible due to the 2 phased build used to produce the final image.

**Comment by edannenberg** [comment]
I guess if any of the nested/sub docker build [proposals](https://github.com/docker/docker/issues/7115) make it through docker hub auto builds should be possible in theory. Would probably lose the ability to utilize the binary package cache though, plus I would feel kinda dirty to offload this rather heavy lifting to docker hub servers.

Feel free to reopen if you got any further questions.
