### ISSUE TITLE
gentoobb/glibc rootfs.tar lacks compiled locale-archive

### ISSUE THREAD

**Issue by azhuang** [edannenberg/gentoo-bb#24]
The reference gentoobb/glibc image, which is served as base image for all glibc-based containers, doesn't copy compiled locale-archive to rootfs.tar when building.

You will encounter locale errors
```
~ docker run -i -t gentoobb/glibc
/ # locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
POSIX
```

This is because locale-gen will generate compiled locale-archive into /usr/lib/locale/locale-archive, while this specific file isn't copied into rootfs.tar. BTW gentoo-bb is based on gentoo nomultilib profile, then /usr/lib is actually a symlink to /usr/lib64.

The locale-gen source has been removed when building gentoobb/glibc image, thus you can no longer rebuild locale inside container by running locale-gen.

To solve this problem I added manually locale-archive to $EMERGE_ROOT before tar'ing the rootfs.

In gentoo-bb/dock/gentoobb/images/glibc/Buildconfig.sh
```
# Add following lines into either configure_rootfs_build() or finish_rootfs_build()

# copy complied locales into rootfs
mkdir -p $EMERGE_ROOT/usr/lib64/locale
cp /usr/lib64/locale/locale-archive $EMERGE_ROOT/usr/lib64/locale/
```

**Comment by edannenberg** [comment]
Thanks for reporting/fixing @azhuang. :+1:  I placed the fix into configure_bob() hook for better readability.
