### ISSUE TITLE
/tmp/downloads not exist

### ISSUE THREAD

**Issue by azhuang** [edannenberg/gentoo-bb#25]
I didn't notice this bug until I was working on a machine behind proxy.

The first time when `build.sh` is run, it will pull portage tree then stage3 tarball and save them to `./tmp/downloads`. While `/tmp/downloads/` doesn't exist (maybe git ignored it as it was empty), the builder will try to pull portage tree inside container when building `bob-core`. There's no proxy configuration inside container so that emerge failed.

In `./inc/core.sh` at line 41:
 https://github.com/edannenberg/gentoo-bb/blob/956a25034bdf7f0ae3e7b2b580bf66159d845b38/inc/core.sh
`[ -d ${DL_PATH} ] || mkdir ${DL_PATH}`
`mkdir` missing -p here.
at line 88 `-p` is there for stage3 downloading so `stage3-import` is built correctly.

**Comment by edannenberg** [comment]
Oops. Thanks for reporting. Should be fixed by the weekend. Feel free to open a PR.
