### ISSUE TITLE
Layman support?

### ISSUE THREAD

**Issue by rbarrois** [edannenberg/gentoo-bb#27]
Hi,

This project looks pretty awesome! A single question remains for me though: how should I load a custom overlay into my builder?

Thanks :)

**Comment by edannenberg** [comment]
Thanks.

Basically like you always do. If your builder is based on the `gentoobb/bob` image it should be as simple as running `layman -a foo` in the `configure_bob()` hook of your builder's `Buildconfig.sh`. Then set your builder as the [default build container](https://github.com/edannenberg/gentoo-bb/blob/master/dock/gentoobb/build.conf) for your namespace.

Check the [bob-musl](https://github.com/edannenberg/gentoo-bb/blob/master/dock/gentoobb/builder/bob-musl/Buildconfig.sh#L24) builder for an example.
