### ISSUE TITLE
ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header

### ISSUE THREAD

**Issue by edannenberg** [edannenberg/gentoo-bb#28]
Regression in docker 1.10.0-1.10.1. See https://github.com/docker/docker/issues/20296.

Stick with docker 1.9.x for building until 1.10.2 is out.

**Comment by jbergstroem** [comment]
Seems to be fixed in 1.10.2 (1.10.3 is latest in gentoo; could you help bumping?)

**Comment by edannenberg** [comment]
Most people probably have a fixed version now.
