### ISSUE TITLE
./build.sh fails to find gentoobb/stage3-import:latest

### ISSUE THREAD

**Issue by k2t0f12d** [edannenberg/gentoo-bb#36]
Whilst logged in with docker, I was not able to build bob.

~/dev/gentoo-bb $ ./build.sh
--> generate build order
--> required engines:  dummy docker
--> required builders: dummy/bob-core gentoobb/bob gentoobb/bob-musl
--> build sequence:    dummy/busybox gentoobb/busybox gentoobb/glibc gentoobb/s6 gentoobb/openssl gentoobb/bash gentoobb/cadvisor gentoobb/jre-oracle gentoobb/clojure gentoobb/docker-registry gentoobb/elasticsearch gentoobb/gcc gentoobb/grafana gentoobb/influxdb gentoobb/jdk-icedtea gentoobb/jdk-oracle gentoobb/kibana gentoobb/ruby-gcc gentoobb/log-collector gentoobb/mariadb gentoobb/memcache gentoobb/mysql gentoobb/nginx gentoobb/nginx-php5.5 gentoobb/nginx-php7 gentoobb/nginx-proxy gentoobb/nginx-proxy-conf gentoobb/nodejs gentoobb/opensmtpd gentoobb/postgres gentoobb/python2 gentoobb/python3 gentoobb/redis gentoobb/riemann gentoobb/riemann-dash gentoobb/ruby
--> validate dummy engine
--> building dummy core
--> build gentoobb/stage3-import
--> build repo gentoobb/bob-core
--> build gentoobb/bob-core:20160616
Sending build context to Docker daemon 20.48 kB
Step 1 : FROM gentoobb/stage3-import
Pulling repository docker.io/gentoobb/stage3-import
Error: image gentoobb/stage3-import:latest not found
failed to build gentoobb/builder/bob-core

**Comment by edannenberg** [comment]
Hmm odd, so this works if you are not logged in with docker hub?

Please post the output of:

    $ docker images | grep gentoobb

Also what Docker version are you running? I'll try to reproduce the error later today.

**Comment by k2t0f12d** [comment]
~/dev/gentoo-bb $ docker images | grep gentoobb
gentoobb/stage3-import   20160623            65474c2edd52        15 hours ago        791.3 MB
gentoobb/stage3-import   20160616            bbba098541e4        16 hours ago        791.4 MB

~/dev/gentoo-bb $ docker -v
Docker version 1.12.0-rc2, build 906eacd

Despite seeing those, the build continues to fail.

**Comment by edannenberg** [comment]
This is a follow up error, `docker tag -f` got removed in Docker 1.12, hence the  `latest` tag was missing. After pulling the fix run `$ docker rmi -f 65474c2edd52  bbba098541e4` to remove the existing stage3-import and rebuild.

**Comment by k2t0f12d** [comment]
Yay! Thanks :)

**Comment by edannenberg** [comment]
Your welcome. Thanks for reporting.
