### ISSUE TITLE
nginx-php7 error

### ISSUE THREAD

**Issue by soredake** [edannenberg/gentoo-bb#37]
```
--> tag gentoobb/nginx:latest
--> build repo gentoobb/nginx-php7
--> building rootfs
--> run gentoobb/bob-nginx:20160929
At argv[6]='+gd': Ambiguous argument: gd (matches lic, use).
Aborting.
failed to run image gentoobb/bob-nginx:20160929
```

**Comment by edannenberg** [comment]
Will need to take a closer look for that one, but monthly rebuild is coming up anyways.

**Comment by edannenberg** [comment]
At argv[6]='+gd': Ambiguous argument: gd (matches lic, use).

A flaggie issue, `lic` refers to license, apparently there now is a name conflict for the `gd` use flag. Guess this one has to be handled manually now as there seems to be no option in flaggie to resolve this.
