### ISSUE TITLE
nginx-php7,  flaggie error

### ISSUE THREAD

**Issue by soredake** [edannenberg/gentoo-bb#40]
```
--> build repo gentoobb/nginx-php7
--> building rootfs
--> run gentoobb/bob:20161020
At argv[2]='+~amd64': ~amd64 seems to be an incorrect keyword for app-eselect/eselect-php
```

**Comment by edannenberg** [comment]
Should be fixed with https://github.com/edannenberg/gentoo-bb/commit/4d7c9cdfb4a90d956a58eb7425bb88d3888e294f#diff-f7545f3e65835bf1f1111af07a8d4ad4L17

Please double check you are on latest master.

**Comment by soredake** [comment]
Double checked, i'm on master. Maybe time to replace flaggie with pure bash code?

**Comment by edannenberg** [comment]
It's not really a flaggie issue in this case. There currently is no `app-eselect/eselect-php` version in unstable tree, yet somewhere in your config you try to set `~amd64` keyword for it. So flaggie complains. 

A full rebuild shouldn't be required. Just the image:

    ./build.sh -nF <image>
