### ISSUE TITLE
Dockerfile.template is missing in sass-gulp image

### ISSUE THREAD

**Issue by soredake** [edannenberg/gentoo-bb#55]
```
./build.sh -sfFcC build gentoobb
--> generate build order
sed: can't read gentoobb/images/sass-gulp/Dockerfile.template: No such file or directory
error executing get_image_builder(): error while generating gentoobb/images/sass-gulp/Dockerfile
```

**Comment by edannenberg** [comment]
The image isn't public yet, the `PACKAGES.md` file slipped trough though with the last stage3 update. :/ Just delete the `sass-folder` folder for now, will fix on master tomorrow.

**Comment by soredake** [comment]
And one more thing, now i catch the 
```
--> build gentoobb/bob-core:20161229
Sending build context to Docker daemon  5.12 kB
Step 1 : FROM gentoobb/stage3-import
 ---> 76b0763f5b7a
Step 2 : MAINTAINER Erik Dannenberg <erik.dannenberg@bbe-consulting.de>
 ---> Using cache
 ---> 2ec2133d03c2
Step 3 : RUN echo 'GENTOO_MIRRORS="http://distfiles.gentoo.org/"' >> /etc/portage/make.conf &&     mkdir -p /etc/portage/repos.conf /usr/portage &&     sed -e 's|^sync-uri =.*|sync-uri = rsync://rsync.europe.gentoo.org/gentoo-portage|'         -e 's|^sync-type =.*|sync-type = rsync|'         /usr/share/portage/config/repos.conf > /etc/portage/repos.conf/gentoo.conf &&     chown -R portage:portage /usr/portage &&     emerge-webrsync -k &&     eselect news read new 1>/dev/null &&     mkdir -p /etc/portage/profile &&     if [[ ${BOB_DO_SYNC} == "true" ]]; then emerge --sync; else true; fi
 ---> Using cache
 ---> a8ff463aedf8
Step 4 : COPY make.conf /etc/portage/make.conf
lstat make.conf: no such file or directory
failed to build gentoobb/builder/bob-core
```
on all my machine on vanilla gentoobb even after deleting the /var/lib/docker, am I doing something wrong?
I have no idea why I get so many strange errors and how to fix them.

**Comment by edannenberg** [comment]
There is some special handling involved when building `bob-core`, see [docker.inc](https://github.com/edannenberg/gentoo-bb/blob/master/inc/engine/docker.sh#L212). So it should never get picked up as a normal build container. I added a [check](https://github.com/edannenberg/gentoo-bb/commit/c9a0ed35608314fdd3080043f4b6213d3c271ddf) which resolves the issue.

Not sure how I didn't have this issue until now (did a complete rebuild from scratch just yesterday), sorry for the inconvenience.

**Comment by soredake** [comment]
@edannenberg 
>Not sure how I didn't have this issue until now (did a complete rebuild from scratch just yesterday), sorry for the inconvenience.

It's okay, i'm glad that i'm at least was able to identify the problem itself.

**Comment by soredake** [comment]
@edannenberg one one more thing, this https://github.com/edannenberg/gentoo-bb/commit/93e1f6ac5f1a55272255511343258e8c115dea9d#diff-c2308669649acc151b909ceaddf153e5R163 change broken PACKAGES.md generation 

```
--> tag gentoobb/busybox:latest
/home/core/git/gentoo-bb/inc/core.sh: line 167: gentoobb/images/busybox/PACKAGES.md: Permission denied
failed to generate PACKAGES.md for gentoobb/images/busybox
```

**Comment by soredake** [comment]
And https://github.com/edannenberg/gentoo-bb/issues/38#issue-183839419 openssh stiil needs `rm` to uninstall.

**Comment by edannenberg** [comment]
Can't confirm those two, maybe CoreOS related? Though I don't really see how at the moment. Did the `PACKAGES.md` generate after reverting that commit?

**Comment by soredake** [comment]
@edannenberg yes, after reverting it generating works. Can't test on gentoo now.

**Comment by edannenberg** [comment]
@jbergstroem any ideas? iirc you had CoreOS too back then.

**Comment by jbergstroem** [comment]
Haven't touched it in a year unfortunately :( Since docker runs natively on MacOS I'm getting lazy.

Speaking of; perhaps its time we try and write some kind of test suite? At least something for our tooling/bash scripts. If nothing else, we could make sure that things like required commands and their output/return works as intended.

**Comment by edannenberg** [comment]
Wouldn't really have helped in this case though, the tests would have ran fine for you and me. Still good to have obv., gonna focus on the acbuild refactor for now though.
