### ISSUE TITLE
Consider USE=minimal on sys-libs/ncurses

### ISSUE THREAD

**Issue by azimut** [edannenberg/gentoo-bb#59]
about 5MB get's removed from /usr/share/terminfo (the ebuild does a rm -rf) alpine does something similar with some backup on /etc http://git.alpinelinux.org/cgit/aports/tree/main/ncurses/APKBUILD so far It worked for me but don't know about the images you use

**Comment by edannenberg** [comment]
Nice. Tried the `minimal` flag for ncurses, seems to work but "only" seeing about `1mb` size reduction on my end.

**Comment by edannenberg** [comment]
Looking at `/usr/share/` in the bash image the only big chunk left seems to be `misc/magic.mpc` with around `5mb`. Removing that is probably not a good idea, but providing a minimal version might be an option.

**Comment by azimut** [comment]
right, probably at docker image level is about that, I just base it on "du"
{code}
sh-4.3# du -sh /usr/share/terminfo/
6.7M	/usr/share/terminfo/
{code}
Ha! I will consider removing that on my image.

**Comment by soredake** [comment]
>but probably not applicable here due lack of nodejs support for it
`+bundled-openssl` is solution for now

**Comment by jbergstroem** [comment]
@azimut we (node.js) have a work in progress patch for libressl but it's alpha and isn't on par feature-wise: https://github.com/nodejs/node/pull/9376

**Comment by edannenberg** [comment]
@azimut with the latest changes you should now be able to simplify your repo setup:

```
./rpi-cluster
├── builder
│   ├── bob-armv7a
│   ├── bob-armv7a-musl
│   └── bob-armv7a-musl-libre
└── images
build.conf
README.md
```

Then just clone the whole thing under `gentoobb/dock`.

Set `STAGE3_BASE` for `bob-armv7a` and `bob-armv7a-musl`. `bob-armv7a-musl-libre` can just extend `bob-armv7a-musl` by configuring `BUILDER`. [bob-musl's build.conf](https://github.com/edannenberg/gentoo-bb/blob/master/dock/gentoobb/builder/bob-musl/build.conf) should be pretty much what you want, should be enough to change `STAGE3_BASE` and `ARCH`.

**Comment by azimut** [comment]
@edannenberg That worked, not the easiest migration ever (mainly due I had a typo on CFLAGS that collided with the new approach of force rebuild of bob-core if CFLAGS are changed), but it worked!. I will create other bug for libressl which is the pending topic that appeared here. Any reason to leave this open? I am not building anything that pulls "file" so I can't help with the magic.mgc test.

**Comment by edannenberg** [comment]
Glad it worked out.

> the new approach of force rebuild of bob-core if CFLAGS are changed

Was sadly no other way around it. `CFLAGS` need to be defined per stage3 build container now, with only one stage3 we could just export the namespace/global default, but now this context may no longer be accurate after the stage3 build container is built.

> Any reason to leave this open? I am not building anything that pulls "file" so I can't help with the magic.mgc test.

`magic.mgc` will probably amount to 1MB image size, so gain/pain ratio fiddling with that is not really worth it IMO. Closing. :)
