### ISSUE TITLE
avoid docker slices for multiple env's

### ISSUE THREAD

**Issue by jbergstroem** [edannenberg/gentoo-bb#60]
in `Dockerfile` you can pass:
```Dockerfile
ENV foo=bar \
  bar=baz \
  qux="foo bar"
```
..to avoid the multiple layers of images. Lets do this for our builders.

(not doing a PR atm since it's against the multistage3 branch)

**Comment by edannenberg** [comment]
As max layers are limited probably a good idea, also moved the `ENV` command further down for possible cache leverage on rebuild.

**Comment by edannenberg** [comment]
Of course I missed the `=` which is required for multi assignments but not for singe. ><
One downside to be aware of is that prev. defined ENV are not available inside a single ENV instruction:

```
# works
ENV foo $bar
ENV meh $foo

# doesn't
ENV foo=$bar \
    meh=$foo
```

One last thing I currently can't wrap my head around is this https://github.com/edannenberg/gentoo-bb/commit/3bd09c714ecbb505ae30821928252a1702fd4845

If the default is set it seems to override the actual value, removing the default fixes the issue. But the same thing works for `BOB_BUILDER_CHOST` down a few lines. Also fairly sure this worked before refactoring to multi assignment. Not sure what I'm overlooking here.
