### ISSUE TITLE
Add new image/builder from template

### ISSUE THREAD

**Issue by edannenberg** [edannenberg/gentoo-bb#61]
Basically take care of most of the boilerplate by running something like:

    ./build.sh add namespace foo
    ./build.sh add image foo/bar
    ./build.sh add builder foo/baz

- [x] Create a namespace 
- [x] Create an image
- [x] Create a builder

**Comment by edannenberg** [comment]
I've added helpers for namespace and images along with updated quick start in `README.md` and a (hopefully) thoroughly documented `build.sh` for images.

/cc @jbergstroem @berney

**Comment by berney** [comment]
Looks good, a nice addition.
