### ISSUE TITLE
Quick Start Documentation Doesn't Work

### ISSUE THREAD

**Issue by berney** [edannenberg/gentoo-bb#62]
The Quick Start documentation states: -

```
$ git clone https://github.com/edannenberg/gentoo-bb.git
$ cd gentoo-bb
$ ./build.sh
```

I do a git clone, cd into the directory and try the `./build/sh`: -

```
gentoo@gentoo ~/gentoo-bb $ ./build.sh
--> generate build order
failed to expand requested images, typo in namespace or image name?
```

Reading the README.md, and I'm now reading the code to try to work out how to get started.

**Comment by edannenberg** [comment]
Looks like the `dummy` namespace throws a wrench now, as the name suggests not terribly important. :p As a workaround you can target a namespace or image like so:

    $ ./build.sh build gentoobb
    $ ./build.sh build gentoobb/nginx

Fix should be up shortly.

**Comment by edannenberg** [comment]
I have updated the `README.md` for the recent changes regarding image structure.

**Comment by berney** [comment]
Thanks @edannenberg I've now gotten much further with using this tool, which seems awesome, thanks for sharing your hard work. I fixed a small issue and sent your a PR #65.

**Comment by edannenberg** [comment]
Thanks, merged. Feel free to add further questions to #43, many things are all to natural for me at this point so any feedback is very helpful for improving the documentation.

**Comment by berney** [comment]
Thanks I'll ask further questions on #43 so that it may help on improving the documentation.
