### ISSUE TITLE
invalid package name in package.provided, while building glibc after busybox

### ISSUE THREAD

**Issue by UralZima** [edannenberg/gentoo-bb#69]
Hi. I am building anything from scratch using yesterday's clonned code
I just changed builder for busybox to bob.

On building glibc, I receive multiple messages

removing intermediate container 27a602fcd302
Successfully built 38348d736218
--> tag bb/busybox:latest
--> build repo bb/glibc
--> building rootfs
--> run bb/bob-busybox:20170127
 * Generating locale-archive: forcing # of jobs to 1
 * These locales have been duplicated in your config:
en_US.UTF-8 UTF-8
en_US.UTF-8 UTF-8
 * Some might be filtered, but you must fix it.
 * Generating 2 locales (this might take a while) with 1 jobs
 *  (1/2) Generating en_US.ISO-8859-1 ...                                                                                                                           [ ok ]
 *  (2/2) Generating en_US.UTF-8 ...                                                                                                                                [ ok ]
 * Generation complete
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
See portage(5) for correct package.provided usage.
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
See portage(5) for correct package.provided usage.
At argv[2]='+~amd64': ~amd64 seems to be an incorrect keyword for sys-devel/libtool
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
See portage(5) for correct package.provided usage.
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
See portage(5) for correct package.provided usage.
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
See portage(5) for correct package.provided usage.
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
See portage(5) for correct package.provided usage.
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
See portage(5) for correct package.provided usage.
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
See portage(5) for correct package.provided usage.
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
See portage(5) for correct package.provided usage.
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
See portage(5) for correct package.provided usage.
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
See portage(5) for correct package.provided usage.

then

Calculating dependencies... done!
[binary  N     ] sys-apps/baselayout-2.3::gentoo to /emerge-root/ USE="-build" 0 KiB

Total: 1 package (1 new, 1 binary), Size of downloads: 0 KiB

>>> Emerging binary (1 of 1) sys-apps/baselayout-2.3::gentoo for /emerge-root/
>>> Installing (1 of 1) sys-apps/baselayout-2.3::gentoo to /emerge-root/
>>> Jobs: 1 of 1 complete                           Load avg: 6.2, 10.0, 8.8

 * Messages for package sys-apps/baselayout-2.3 merged to /emerge-root/:

 * Initializing /emerge-root/lib as a symlink
 * Initializing /emerge-root/usr/lib as a symlink
 * Initializing /emerge-root/usr/local/lib as a symlink
 * You should reboot the system now to get /run mounted with tmpfs!
>>> Auto-cleaning packages...

>>> Using system located in ROOT tree /emerge-root/

>>> No outdated packages were found on your system.

 * IMPORTANT: 5 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
Invalid package name in package.provided: sys-apps/portage-2.3.3::gentoo
See portage(5) for correct package.provided usage.
Invalid package name in package.provided: sys-apps/busybox-1.25.1::gentoo
Invalid package name in package.provided: sys-apps/portage-2.3.3::gentoo
See portage(5) for correct package.provided usage.

glibc is still building. why this is caused?

**Comment by UralZima** [comment]
these messages repeating for every newly built container, containing error about every newly installed packages. Maybe it is because of ::gentoo tag?

**Comment by edannenberg** [comment]
Those are just warnings from portage so it didn't affect the build. As to why, I'm not sure, the duplicated `en_US.UTF-8 UTF-8` warning suggests something is up with the build container state. Try:

    $ ./build.sh clean
    $ ./build.sh -C build bb

This should rebuild everything from scratch. If the issue persists it might be related to your namespace rename, which would be a bug. Can you push your changes to a fork so I can take a closer look?

**Comment by UralZima** [comment]
I did a clean before building. 
I issued a command ./build.sh build bb/mariadb
I am very sorry, I don't learned git and it is hard for me to commit, fork, push etc.
I just gzipped my folder and uploaded it here: https://www.sendspace.com/file/k7qmew
What was changed:
0. Removed all unnecessary packages folders. Renamed namespace to bb
1. Added lines to bob's build.sh to upgrade gcc
2. removed --clean and --strict from flaggie, it caused errors when I updated_keywords to (maybe) insexistent packages
3. created php5.6 container separately
4. updated mariadb to ~amd64 version
5. busybox changed builder to bob
6. etc
For you it's easier to diff and see what changed. 

P.S. you have a bug in nginx-php5.6 container, the etc folder inside contains php-fpm5.5 folder with php-fpm.conf, and it fails to start

Thank you for help

**Comment by UralZima** [comment]
I can't rebuild everything, because it is still building all the day... very long time. Even right now I am only at openssl

**Comment by edannenberg** [comment]
Ok, no worries. I'll take a look tomorrow. Thanks for the php5.6 hint, will fix.

Try to learn git sometime in the future, makes live so much easier and takes no time at all. :)

Some resources:

https://guides.github.com/activities/hello-world/
https://wildlyinaccurate.com/a-hackers-guide-to-git/

**Comment by UralZima** [comment]
Thanks for links. Will take a look. I hope this package.provides errors will not fail my build and I don't need to build it again from scratch... I get bunch of such errors after each container was built.  I think it is because ::gentoo tag is added to this file, on my host I don't have any tag after package name. Can't find it where it can add in your code

**Comment by edannenberg** [comment]
Once you have all the binary packages in your local cache a rebuild should be much quicker. Out of curiosity, what are your build host specs? (cpu/ram)

**Comment by UralZima** [comment]
amd 4 core/16GB, gentoo hardened. Running inside KVM/Qemu right now temporarily...

**Comment by edannenberg** [comment]
Ah the KVM stuff might be the bottle neck then. As I said, for every installed package a binary package is placed in `./gentoo-bb/tmp`. This is mounted by all build containers as Portage's `PACKAGES` folder, so unless you switch use flags there shouldn't be any compiling on rebuilds except for new packages.

**Comment by UralZima** [comment]
Yeah I know, very useful feature :) ok will see how it will finish and run. Thanks
P.S. right now it is building bash, it includes coreutils package as dep, so it seems I can remove busybox from my packages. Will try to rebuild all.. In that way, it must use binary packages too, I think

**Comment by UralZima** [comment]
Hi. I tried again to build all from scratch, removed tmp and did clean. Renamed namespace back to gentoobb. I receive same package.provided errors, right after building busybox with bob. And receive errors for every package. Seems to be a bug

**Comment by UralZima** [comment]
Hm. Maybe it is because I added -v to emerge default flags. I think this is issue

**Comment by UralZima** [comment]
Hi. Sorry about to be confused with that issue. I just wanted emerge to be more verbose and this caused an error. 
Also, wanted to add, in file I uploaded to sendspace, I have modified nginx container, coz in mwa overlay it don't have all modules, and pagespeed outdated. I modified it to use ~amd64 nginx and  download and compile latest pagespeed. Please take a look. You may commit these changes to your nginx package, just need to add pagespeed version to some variable and get version online. It builds and runs successfully, latest nginx with latest pagespeed.
