### ISSUE TITLE
bob-musl gcc-config

### ISSUE THREAD

**Issue by azimut** [edannenberg/gentoo-bb#77]
Wondering why gcc was not switched to hardened on bob-musl. If there is a reason, I imagine stability. Can be added as a comment somewhere?

**Comment by edannenberg** [comment]
Yea I just went with the defaults, same goes for `bob`. I'll enable hardened on `bob` for the next build, if it works out I'll make it default. Feel free to make a PR for `bob-musl` (or `bob` for that matter) if the hardened profiles are painless for you.

**Comment by azimut** [comment]
#79 submitted

**Comment by edannenberg** [comment]
As discussed in the PR, this is a quirk of the arm stage3, which enables the vanilla profile per default. Probably not without reason, so we leave that decision to each user.
