### ISSUE TITLE
Invalid package name in package.provided

### ISSUE THREAD

**Issue by UralZima** [edannenberg/gentoo-bb#78]
Hello. 
I receive again package.provided errors, and can't figure out why. It is kind of mysterious. 
All was fine, but as I updated gcc, I got some linking errors, and I decided to rebuild anything in bob after updating gcc.
what I added in configure_bob()

    update_keywords 'sys-devel/libtool' '+~amd64'
    update_keywords 'sys-devel/gcc' '+~amd64'
    update_keywords 'sys-devel/binutils' '+~amd64'
    update_keywords 'sys-devel/crossdev' '+~amd64'
    update_keywords 'dev-lang/go' '+~amd64'

    emerge -v gcc
    gcc-config x86_64-pc-linux-gnu-5.4.0
    source /etc/profile
    emerge -v binutils
    binutils-config x86_64-pc-linux-gnu-2.27
    source /etc/profile
    emerge -v libtool glibc
    emerge -C gcc-4.9.4
    emerge -Deuv --with-bdeps=y @system @world # rebuild anything to not cause build errors
    source /etc/profile

    emerge -v sys-devel/crossdev dev-vcs/git app-portage/layman sys-devel/distcc

bob built fine, busybox too.

now, when glibc is building, I receive such errors:
Invalid package name in package.provided: sys-libs/timezone-data-2016h-1
Invalid package name in package.provided: sys-apps/portage-2.3.3-1
Invalid package name in package.provided: sys-libs/glibc-2.23-r3-1
Invalid package name in package.provided: sys-apps/gentoo-functions-0.10-1

It is adding '-1' to the end. Why? 

on next builds, like bash etc I receive more such errors. and -1 is not added to all packages.

I tried to debug this function, but can't get any output of 
provide_package() {
    for P in ${@}; do
        emerge -p "${P}" | grep "${P}" | grep -Eow "\[.*\] (.*) to" | awk '{print $(NF-1)}' >> /etc/portage/profile/package.provided
    done
}
if I run it manually. 
P=bash
emerge -p "${P}" | grep "${P}" | grep -Eow "\[.*\] (.*) to" | awk '{print $(NF-1)}'  # print nothing
emerge -p "${P}" | grep "${P}" | grep -Eow "\[.*\] (.*) to" # print nothing

Please help me to fix it or debug provide_package function, or it comes from packages_installed... 
Can't understand

Thanks

**Comment by UralZima** [comment]
List of package.provided in gentoobb/bob-bash

sys-apps/busybox-1.25.1
sys-apps/portage-2.3.3-1
sys-apps/gentoo-functions-0.10-1
sys-libs/timezone-data-2016h-1
sys-libs/glibc-2.23-r3-1
dev-libs/skalibs-2.4.0.2
dev-lang/execline-2.2.0.0
sys-apps/s6-2.4.0.0
app-misc/c_rehash-1.7-r1-1
sys-libs/zlib-1.2.11-1
sys-apps/debianutils-4.7-1
app-misc/ca-certificates-20161102.3.27.2-r2-1
dev-libs/openssl-1.0.2k-2
sys-libs/zlib-1.2.11-1
sys-libs/ncurses-6.0-r1
sys-apps/attr-2.4.47-r2-1
app-arch/bzip2-1.0.6-r7-1
sys-libs/e2fsprogs-libs-1.43.3-1
app-misc/c_rehash-1.7-r1-1
dev-libs/iniparser-3.1-r1-1
sys-apps/debianutils-4.7-1
dev-libs/libffi-3.2.1-1
sys-libs/readline-6.3_p8-r3-1
sys-apps/acl-2.2.52-r1-1
sys-apps/file-5.29-1
app-misc/ca-certificates-20161102.3.27.2-r2-1
app-portage/portage-utils-0.62-1
sys-apps/util-linux-2.28.2-1
sys-apps/coreutils-8.25-1
app-shells/bash-4.3_p48-r1-1
dev-libs/libpcre-8.39-1
dev-libs/libxml2-2.9.4-r1-1
dev-libs/openssl-1.0.2k-2
sys-fs/e2fsprogs-1.43.3-r1-1
sys-apps/sed-4.2.2-1
sys-libs/slang-2.3.0
net-misc/curl-7.52.1-r1-1
app-admin/eselect-1.4.5-1
app-eselect/eselect-vi-1.1.7-r1
app-eselect/eselect-ctags-1.18
dev-util/ctags-20161028
dev-libs/glib-2.48.2-1
x11-misc/shared-mime-info-1.4-1
app-misc/mc-4.8.18-r1
app-editors/vim-core-8.0.0106
app-editors/vim-8.0.0106
app-vim/gentoo-syntax-20160530

openssl even have '-2' in the end, and as you see, not all packages have this prefix...

**Comment by UralZima** [comment]
Ok I found how to debug 
P=bash
ROOT="/emerge-root" emerge -p "${P}" | grep "${P}" | grep -Eow "[.] (.) to" | awk '{print $(NF-1)}' 
it print's ok. but on building, it adds -1 or -2. This started happen when I added
emerge -Deuv @system @world in bob, after rebuilding all packages.
I can do a dirty replace with sed, but why this happens?

**Comment by edannenberg** [comment]
Can confirm the issue with the provided example gcc5 setup. The reason this worked in `bob-interactive` shell is that you probably didnt run `source /etc/profile` before. Apparently related to https://github.com/edannenberg/gentoo-bb/commit/322f375b0a4d127c2ad3e8357bffb98c348b7b16. After upgrading gcc this causes the `-1` suffix you are seeing, it denotes the current binary package slot. Fix should be up shortly.

PS: rebuilding world seems kinda overkill, this should probably save you a bunch of time with practically the same result:

```
    update_keywords 'sys-devel/gcc' '+~amd64'
    update_keywords 'sys-devel/binutils' '+~amd64'
    emerge -v gcc app-portage/gentoolkit
    gcc-config x86_64-pc-linux-gnu-5.4.0
    env-update && source /etc/profile
    #binutils-config x86_64-pc-linux-gnu-2.27
    emerge -v --oneshot libtool
    revdep-rebuild
    emerge -C gcc-4.9.4
```

**Comment by edannenberg** [comment]
Please pull latest changes and rebuild, should be resolved now.

**Comment by UralZima** [comment]
Thanks for fast fix. Why I did a full emerge rebuild, because php crashed with incompatible ABI, required by libicu. when I tried revdep-rebuild on my home workstation, it did nothing...

1. do I need to rebuild the full stack now? Or I can work normally with my dirty sed 's/-[0-9]$//g' fix while next rebuild? 
2. If yes, Is it possible to rebuild bob only, and not rebuild the full stack? or it is nested and everyting depends on it? 
3. How to debug failed emerge? I can't read /var/tmp/portage/**log, coz container is stopped. Is there any way to failback to bash in case of fail? Bob-interactive don't help me much, I need to do update_* anything manually, I can't understand how it works, no any documentation on that. If I want to do manual emerge, I need to manually define all from configure_* functions. 
4. If you want, you can add my fix to php5.6 package for GCC 5 (you can add a check for it)
configure_bob()
{
    mkdir /etc/portage/env
    echo 'CFLAGS="${CFLAGS} -fgnu89-inline"' > /etc/portage/env/mem
    echo 'dev-php/pecl-memcache mem' >> /etc/portage/package.env
}

Thanks

**Comment by UralZima** [comment]
Ok about question 3 it seems it is possible to debug emerge after failed build-root, coz it saves all flags/etc. after successful run of build-root om bob-interactive, how to commit it, instead of re-running ./build.sh build?

**Comment by edannenberg** [comment]
> do I need to rebuild the full stack now? Or I can work normally with my dirty sed 's/-[0-9]$//g' fix while next rebuild?

You should do a full rebuild yes.

> If yes, Is it possible to rebuild bob only, and not rebuild the full stack? or it is nested and everyting depends on it?

When you rebuild a image you will also need to rebuild all images that depend on it. When changing a builder image this usually means a full rebuild.

> How to debug failed emerge? I can't read /var/tmp/portage/log, coz container is stopped. Is there any way to failback to bash in case of fail? 

Unless `--rm` is passed or a container failed, stopped containers are not removed, you can list those with `docker ps -a`. From there you have a couple of options:

1. Inspect logs/files by copying them to host: `docker cp <buildcontainer_id>:/path/somelog /hostpath/`
2. Run old build container by committing it as new image: `docker commit <buildcontainer_id> foo && docker run -it --rm foo bash`, which gives you the exact filesystem state when the build failed

> Bob-interactive don't help me much, I need to do update_ anything manually, I can't understand how it works, no any documentation on that. If I want to do manual emerge, I need to manually define all from configure_ functions.

There are usually 2 use cases for `bob-interactive`:

1. Prototype a new image:

* `source /etc/profile`, then run emerge -pv on packages of interest to determine use flags, etc
* setup `build.sh` for image accordingly, exit and start the build

2. Troubleshoot existing image:

* `build-root foo` starts the build => fix errors, exit and rebuild image with `-n` option

> If you want, you can add my fix to php5.6 package for GCC 5 (you can add a check for it)

The `gentoo-bb` namespace will most likely always stay with default gcc profile, but if this can be cleanly integrated without too much noise I'm not opposed to a PR. ;)

> after successful run of build-root om bob-interactive, how to commit it, instead of re-running ./build.sh build?

`bob-interactive` is just for testing/trouble shooting, it should never be used to produce a final image. This is mainly to ensure build repeatability. You don't want to scratch your head next month when it's update time and you don't remember that one manual step you did in bob-interactive.

**Comment by UralZima** [comment]
Ok thanks for the answers. About bob-interactive you should add it to readme.md. Someday I'll learn git and will push my changes somewhere in a fork, I have some new packages prepared, like citadel mail server, ffmpeg and phantomjs. 
Also, for nginx, mariadb and php-fpm I use shared-volume socket dirs, instead of linking and exposing ports, that's much better, faster and stable way to use it. 

I wish someday to see gentoobb in portage, or at least some overlay, and to have one executable in /usr/bin that I can run inside by namespace dir :)
Good luck and thanks for good job!

**Comment by edannenberg** [comment]
> Someday I'll learn git and will push my changes somewhere in a fork, I have some new packages prepared, like citadel mail server, ffmpeg and phantomjs.

Please do. I'm sure you can manage a handful of one liners, git is really not that hard as it looks. :nerd_face: 

> Also, for nginx, mariadb and php-fpm I use shared-volume socket dirs, instead of linking and exposing ports, that's much better, faster and stable way to use it.

Yep, we already have example for that in the image [readme](https://github.com/edannenberg/gentoo-bb/tree/master/dock/gentoobb/images/mariadb).

**Comment by berney** [comment]
> Apparently related to 322f375. After upgrading gcc in the build container this causes the -1 suffix you are seeing, it stands for the used binary package slot. Fix should be up shortly.

I wasn't aware of the suffixes from binpkg-multi-instance. I'm glad the cause was found and fixed.
