### ISSUE TITLE
BOB_CFLAGS not being templated for -core

### ISSUE THREAD

**Issue by azimut** [edannenberg/gentoo-bb#80]
Really tired to keep debugging. I do set the cflags on build.conf on root and on the builder.
```
> grep '^BOB_CFL' build.conf dock/gentoobb/builder/bob-musl/build.conf 
build.conf:BOB_CFLAGS="-O2 -march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard"
dock/gentoobb/builder/bob-musl/build.conf:BOB_CFLAGS="-O2 -march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard"
```
But in the resulting dock/gentoobb/builder/bob-musl-core/Dockerfile always had:
```
DEF_CFLAGS="-mtune=generic -O2 -pipe"
```

I change bob-core/Dockerfile.template to:
```
-    DEF_CFLAGS="${BOB_CFLAGS:--mtune=generic -O2 -pipe}" \
+    DEF_CFLAGS="${BOB_CFLAGS}" \
```

And now the template looks fine.

**Comment by azimut** [comment]
Looking now at  generate_dockerfile() I think it shows that the sed doesn't accept defaults. I think.

**Comment by edannenberg** [comment]
I was scratching my head about that too: https://github.com/edannenberg/gentoo-bb/commit/3bd09c714ecbb505ae30821928252a1702fd4845. But didn't have the time yet to investigate further.

I'll just remove the defaults from the `Dockerfile.template` completely, it was kinda redundant any ways as defaults are provided via global build.conf.
