### ISSUE TITLE
binpkg-multi-instance not working properly?

### ISSUE THREAD

**Issue by UralZima** [edannenberg/gentoo-bb#84]
Hi. I use your latest master.
I have a package, which is built on top of php7, it contains ffmpeg, phantomjs and node's npm
First time I built it all was fine. It was built I was happy.
Next time I made a minor change to included file and rebuild with
./build.sh -nF build gentoobb/mypackage
First was libpcre. It sais no -lpcre16. It have use flag, but binary provided don't have.
Ok, I unprovided the package and installed again. pcre16 use flag was green and it compiled.

All was fine, next rebuild other thing broke, libxcb. ok, repeating, unprovide and include emerge for it.
I changed nothing in build.sh, really some minor changes in included files or dockerfile. 
Now npm reporting libuv is missing, rebuilt again
and now libxcbcommon failed.  wtf. 
 * Messages for package x11-libs/libxkbcommon-0.7.1:

 * Failed Running aclocal !
 * 
 * Include in your bugreport the contents of:
 * 
 *   /var/tmp/portage/x11-libs/libxkbcommon-0.7.1/temp/aclocal.out
 * ERROR: x11-libs/libxkbcommon-0.7.1::gentoo failed (prepare phase):
 *   Failed Running aclocal !
 * 
and before it phantomjs crashed.

Now I can't build my package to previous state, I don't know what to do, remove all binary folder and do it again... Why this happens?

**Comment by azimut** [comment]
Just an idea. Your builder (the builder of the parent image) might be wrong. What is at your image build.conf?

**Comment by UralZima** [comment]
build.conf:
IMAGE_PARENT="${NAMESPACE}/php7"

With this builder I built everything, including this image first time and it was successful. 
My builder is bob + gcc5 update
Maybe it is binpkg-multi feature causing this. As I said, first build is ok, on next rebuilds with -nF linker error occurs. 
With simple packages, such as nginx, php7 and mariadb rebuild is fine, bob is working well..
This package I am rebuilding is very heavy, it depends from full QT stack, qtwebkit and much more, because of ffmpeg and phantomjs.

**Comment by edannenberg** [comment]
Looks like it could be an issue with https://github.com/edannenberg/gentoo-bb/commit/322f375b0a4d127c2ad3e8357bffb98c348b7b16#diff-afc9a7492d16f123d31765d8deae0fc7R40 yea. Did you try disabling it? Any steps to reproduce this, preferably with a less costly image, would be very helpful.

**Comment by UralZima** [comment]
I didn't try to disable it, I am whole week rebuilding anything and already need it for production. 
After it failed totally, I found that old root.tar was still usable, and I updated it manually. Will rebuild all stack later, on some update. That's my build.sh

#
# build config
#
PACKAGES="media-video/ffmpeg net-libs/nodejs www-client/phantomjs"

configure_bob()
{
	flaggie 'www-client/phantomjs' '+~amd64'
    flaggie 'net-libs/nodejs' '+~amd64'
    flaggie 'media-video/ffmpeg' '+~amd64'
    flaggie 'dev-qt/*' '+~amd64'
	flaggie 'sys-devel/llvm' '+~amd64'
	flaggie 'media-libs/mesa' '+~amd64'
	flaggie 'sys-libs/binutils-libs' '+~amd64'
	flaggie 'x11-*/*' '+~amd64'
	flaggie 'media-libs/libpng' '+~amd64'
	flaggie 'media-video/ffmpeg' '+cpudetection' '+mp3' '+opengl' '+opus' '+theora' '+vaapi' '+vdpau' '+x264' '+x265' '+xvid' '+bzip2' '+encode' '+iconv' '+lzma' '+network' '+openssl' '+postproc' '+vpx' '+vorbis' '+wavpack' '+webp' '+zimg' '+zlib'
	flaggie 'media-libs/zimg' '+~amd64'


    flaggie 'dev-qt/qtcore' '+icu'
    flaggie 'x11-libs/libxcb' '+xkb'
    flaggie 'x11-libs/libxkbcommon' '+X'
    flaggie 'dev-libs/libpcre-8.39' '+pcre16'
    flaggie 'dev-qt/qtwebkit' '+opengl'
    flaggie 'x11-libs/libva' '+X'

    layman -a rindeal
    emerge -v qtcore qtnetwork qtsql #build fails on rootfs
}

#
# this method runs in the bb builder container just before starting the build of the rootfs
#
configure_rootfs_build()
{
	:
}

#
# this method runs in the bb builder container just before tar'ing the rootfs
#
finish_rootfs_build()
{
    copy_gcc_libs
    #layman -d rindeal
}

I think you will have problems with libpcre and libxcb on building this. (linker)
Also, please explain, why some packages are installing to /emerge-root, some not? 
After rebuild, one some packages I have parent ebuilds, on some not. 
Also, I think when packages fail and we emerging it from configure_bob, it works some different way. 
Why they fails in rootfs()? like php and others. Is there any way to do clean emerge without hacks and all to /emerge-root?

Thanks

**Comment by UralZima** [comment]
shitty markdown

**Comment by UralZima** [comment]
it eaten some * in flaggie, in dev-qt must be * and in x11 two *

**Comment by edannenberg** [comment]
Did a quick test switching use flags on `glibc`, `binpkg-multi-instance` seems to work properly on my end. Removed a flag, package got recompiled. Added it again and the old binary package with correct use flags got used.

Perhaps related to gcc5? Try if disabling `binpkg-multi-instance` resolves the issue for you.

**Comment by berney** [comment]
@UralZima #99 might also be related, if binary packages are linking to the wrong libraries etc. Some of the crashes might be related to this.

**Comment by edannenberg** [comment]
@UralZima Any updates on this or is this resolved and can be closed? Thanks.

**Comment by UralZima** [comment]
I think all fine now, my packages are compiled well with spring. Thanks
