### ISSUE TITLE
nodejs might be broken

### ISSUE THREAD

**Issue by azimut** [edannenberg/gentoo-bb#90]
I was going to create an image like nodejs (not needed python deps) and found that is using tbz2 which should be incompatible with `binpkg-multi-instance`. While on it might be you can use $BOB_CHOST there too.

**Comment by edannenberg** [comment]
Yep, good catch. Probably won't have time for this until next week, PR as always welcome.

**Comment by edannenberg** [comment]
Fixed.

@berney the EMERGE_OPT variable used in the commit is probably relevant to your interests.

**Comment by berney** [comment]
Thanks, I'll be sure to use that.

**Comment by berney** [comment]
@azimut 
> found that is using tbz2 which should be incompatible with binpkg-multi-instance

IIRC the `.tbz2` file would have been from an earlier binary package when `binpkg-multi-instance` was not enabled. `emege --usepkg` will use either `.xpak` or `.tbz2` files.
