### ISSUE TITLE
portage git switch

### ISSUE THREAD

**Issue by soredake** [edannenberg/gentoo-bb#98]
Maybe instead of `mkdir empty_dir && rsync -a --delete empty_dir/ "${portage_path}" && rmdir "${portage_path}" empty_dir` we can use a 
`pushd "${portage_path}" &&  git init && git remote add origin https://anongit.gentoo.org/git/repo/gentoo.git && git fetch --depth=1 && git checkout -ft origin/master && popd` if i understand the purpose of the script.
I believe that's faster that delete and re-download.

**Comment by edannenberg** [comment]
If it works for sure. Will give that a try, thanks!

**Comment by edannenberg** [comment]
Turns out clone is the better alternative:

clone:

```
/usr/bin/git clone --depth 1 https://github.com/gentoo-mirror/gentoo.git .
Cloning into '.'...
remote: Counting objects: 155230, done.
remote: Compressing objects: 100% (127806/127806), done.
remote: Total 155230 (delta 31231), reused 75515 (delta 26183), pack-reused 0
Receiving objects: 100% (155230/155230), 80.34 MiB | 4.25 MiB/s, done.
Resolving deltas: 100% (31231/31231), done.
Checking out files: 100% (140384/140384), done.
```

git init/checkout:

```
$ git remote add origin https://github.com/gentoo-mirror/gentoo.git
$ git fetch --depth=1 && git checkout -ft origin/master
remote: Counting objects: 1929154, done.
remote: Compressing objects: 100% (687492/687492), done.
remote: Total 1929154 (delta 1672434), reused 1419235 (delta 1239827), pack-reused 0
Receiving objects: 100% (1929154/1929154), 571.93 MiB | 8.47 MiB/s, done.
Resolving deltas: 100% (1672434/1672434), done.
```

I did however have a [derp](https://github.com/edannenberg/gentoo-bb/commit/b39da52634537dde547d82b911a2f9192887c9b6#diff-236b61fc64f7a8817cfb8ec7b3b3009eL16) in the sync script that would always delete the portage dir.
