### ISSUE TITLE
Portage installs outdated memcached binary package

### ISSUE THREAD

**Issue by edannenberg** [edannenberg/gentoo-bb#99]
Apparently there is an issue with binary packages when it's dependencies update. With the last `memcached` [update](https://github.com/edannenberg/gentoo-bb/commit/167c8606fd5456d564287c60d999628a08182227#diff-8707195a4ab8c17442ead828fbd46f0eR11) a new `libevent` version got pulled in but as the `memcached` version remained the same the binary package linked to the old `libevent` version was used, resulting in runtime errors.

This is the first time this happened in 2 years, maybe related to enabling `binpkg-multi-instance`? /cc @berney

**Comment by berney** [comment]
I haven't experienced any issues with `binpkg-multi-instance` in the past, but that was predominately on full gentoo installs sharing packages off one master builder (the "slaves" could also build but if the master had already they'd use it's binary package). I'd have to analyse the gentoobb dock tree. Maybe `--with-bdeps=y` will make a difference. Is `libevent` coming from a parent image or the `memcached` image?

In single-host usage, the `usebinpkg` and `binpkg-multi-instance` stuff will realise if the dependent libraries are changing and `@preserve-rebuild` will get updated and logs in the emerge etc.

**Comment by edannenberg** [comment]
> Is libevent coming from a parent image or the memcached image?

Same image.

> In single-host usage, the usebinpkg and binpkg-multi-instance stuff will realise if the dependent libraries are changing and @preserve-rebuild will get updated and logs in the emerge etc.

I see, hmm should work then as the build container is not much different in that regard. The differing `ROOT` shouldn't matter in this context I would guess.

To reproduce the issue masking `dev-libs/libevent-2.1.8` for the `memcached` build first before rebuilding without the mask should do the trick.

**Comment by edannenberg** [comment]
Seems not related to `binpkg-multi-instance`, got the same behaviour without it.

```
./bin/bob_interactive.sh gentoobb/memcache
source /etc/profile
rm -r /packages/x86_64-pc-linux-gnu/dev-libs/libevent*
rm -r /packages/x86_64-pc-linux-gnu/net-misc/memcached*
echo ">=dev-libs/libevent-2.1.8" > /etc/portage/package.mask/foo
ROOT=/foo emerge -pv memcached
ROOT=/foo emerge -v memcached
rm /etc/portage/package.mask/foo
ROOT=/fooa emerge -pv memcached
emerge -pvuD memcached

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U  ] sys-devel/libtool-2.4.6-r3:2::gentoo [2.4.6-r2:2::gentoo] USE="-vanilla" 0 KiB
[ebuild     U  ] dev-libs/libevent-2.1.8:0/2.1-6::gentoo [2.0.22:0/0::gentoo] USE="ssl threads -debug (-libressl) -static-libs {-test}" 0 KiB
[binary  N     ] net-misc/memcached-1.4.33-1::gentoo  USE="-debug -sasl (-selinux) -slabs-reassign {-test}" 0 KiB

Total: 3 packages (2 upgrades, 1 new, 1 binary), Size of downloads: 0 KiB
```

I guess portage thinks it's ok to use the binary package as a suitable `libevent` version is already installed on the host?

**Comment by edannenberg** [comment]
Nope, something seems borked. Updated `libevent` in the build container, only available version is `2.1.8` yet it still happily installs the `memcached` binary package linked to `2.0.22`.

**Comment by edannenberg** [comment]
@berney If you got a couple of minutes to spare could you try to reproduce this on one your native Gentoo hosts with binary package setup? The steps outlined above should be the same. Just to make sure if this a Portage bug that should be reported upstream or related to this project. Thanks!

**Comment by berney** [comment]
I'll give it a shot today and update for you.

**Comment by berney** [comment]
On my gentoo box, I already have libevent-2.1.8 installed, I masked it, installed memcached into a separate root, and it emerge libevent-2.0.22 but memcached is linked to libevent-2.1.so.6.

I'll unmerge libevent and try again.

I see memcached depends on libevent >= 1.4, so I suspect that because it's all one slot emerge will not see a problem with libevent-2.1.8 being installed and the binary package of memcached. I think if libraries are changing ABIs and need a so number bump maybe they should be in different slots? This is getting into the limits of my knowledge about how it everything really works.

**Comment by berney** [comment]
I can reproduce the issue after I uninstalled libevent, I did same as your instructions masked 2.1.8, emerged and got 2.0.22, later I removed the mask and the memcached is linked to old SONAMEs but new libevent is installed.

If I install the without a ROOT envar I get the same problem. `revdep-rebuild` (the new python version) finds the issue.

I think the problem is that memcached says it needs >= libeven-1.4, and between libevent-2.0.22 and libevent-2.1.8 the SONAMEs have changed but it's the same slot. If it was installed into `/` rather than `ROOT` being overridden `preserved-libs` feature would keep the old libs for memcached around on upgrading libevent but only if memcached was already installed, and it should get added to the `preserved-rebuilds` set.

I don't know how to run `revdep-rebuild` in an alternative root that's minimal (missing gentoolkit etc). The source might need modifying. It would be nice if upstream gentoo added the feature, lddtree has a `-R` for example and emerge has `ROOT=` envvar.

**Comment by berney** [comment]
I found this: https://dev.gentoo.org/~zmedico/tmp/Portage_Improvements.pdf

if you do  `ROOT=/foo emerge -vatK --ignore-soname-deps=n memcached` then it will pull in libevent-2.0.22 because the binary package of memcache needs the older sonames that the older libevent provides.

The problem is it needs to be `--usepkgonly` (`-K`), it won't work with `--usepkg` (`-k`) because it needs the soname metadata that only exists in binary packages, so if the any unbuilt packages are included in the dependency graph it would be missing the necessary information.

**Comment by berney** [comment]
I think for QA and testing we will want an introspective revdep-rebuild like too that will look for broken linkage.

For speedy rebuilds we want a way to use binary packages when possible, and for robustness without breaking dynamic linkage. We need a way to detect that the linkage is broken ideally ahead of time before emerging, then there's two choices, emerge the correct version dependency for the existing binary package, or rebuild from source to match the binary dependency. As it stands today I don't think we can do this ahead of time.

We can try to emerge binary packages only (`-K`) with soname dependency checking, if binary packages don't exist we can emerge with binary packages (`-k`) and then once the binary packages have been built we can try again with binaries only and soname dependency checking, this should detect breakages. Then we can exclude the the binary package to have it rebuilt, creating a new binary package that links to the dependency that emerge chooses this time - future rebuilds with soname checking will get this combo.

Post build we should scan with a revdep-rebuild like tool too, doesn't hurt if it's redundant IMO.

To complicated things if images are going to be layered, missing libraries might be expected. Emerge/Portage has somethings to help there like `soname.provided`, `PROVIDES_EXCLUDE`, and `REQUIRES_EXCLUDE` in portage(5) that might help.

**Comment by edannenberg** [comment]
Thanks for confirming my suspicion, much appreciated. I have created an issue [upstream](https://bugs.gentoo.org/show_bug.cgi?id=611428).

> I found this: https://dev.gentoo.org/~zmedico/tmp/Portage_Improvements.pdf
The problem is it needs to be --usepkgonly (-K), it won't work with --usepkg (-k) because it needs the soname metadata that only exists in binary packages, so if the any unbuilt packages are included in the dependency graph it would be missing the necessary information.

Nice find, so close, but no cigar yet. I wonder why Portage not just assumes it needs to rebuild if it can't find all the required binary packages. Seems like a logical conclusion.

> I think for QA and...

I was entertaining the thought to always install at the build container's `/` first before installing at the custom `ROOT` for a while, this would basically remove all friction with missing build dependencies, etc. But the impact on build time is quite high. Something I would like to avoid. `revdep-rebuild` could be nice, but as you said I'm not sure how will this work with a custom `ROOT`. Something for the ever growing backlog. :cry:

> To complicated things if images are going to be layered, missing libraries might be expected. Emerge/Portage has somethings to help there like soname.provided

`package.provided` was enough so far, but yea in some cases depending builds will need to install a package  from a previous image again if it is needed at build time. Can't think of a good way around that and it's actually not that often required, well at least for my images so far.

**Comment by UralZima** [comment]
Let's everybody subscribe on upstream bug report to resolve it faster

**Comment by berney** [comment]
> I was entertaining the thought to always install at the build container's / first before installing at the custom ROOT for a while, this would basically remove all friction with missing build dependencies, etc. But the impact on build time is quite high. Something I would like to avoid. revdep-rebuild could be nice, but as you said I'm not sure how will this work with a custom ROOT. Something for the ever growing backlog. 😢

I think my algorithm I stated above should work for emerging correct packages with working soname dependencies whislt trying to minimal wasted time rebuilding packages that have already been built..To reiterate more clearly it would be: -
  1. Try emerging binary packages only with soname dependency checking: `emerge --usepkgonly --ignore-soname-deps=n ...`.
  2. If above worked to goto end else goto 3
  3. emerge packages from binaries and source: `emerge --usepkg ...`.
      - This will generate soname metadata
  4. Try emerging binary packages only with soname dependency checking: `emerge --usepkgonly --ignore-soname-deps=n ...`.
   5. If above worked goto end else goto 6
   6. try emerging packages with binary package ignored: `emerge --usepkg --usepkg-exclude $atom ...`, where $atom is the main package like `memcached`.
       - This should build main package from source, and dependencies from binaries if they exist and/or source if not
   7. Try emerging binary packages only with soname dependency checking: `emerge --usepkgonly --ignore-soname-deps=n ...`.
   8. If this works goto end else...
   9. ...
    10. Try emergy from source only: `emerge ...` (no `--usepkg`)
    11. Try emerging binary packages only with soname dependency checking: `emerge --usepkgonly --ignore-soname-deps=n ...`.
       - This should work otherwise portage/ebuilds/packages or gentoo/system are broken. 

The above is a bit recursive, at some point it's probably best to switch to rebuilding it all from source and not using any binary packages, producing new binaries packages.

Alternatively a `revdep-rebuild`-like tool that works on specified roots. I think this should be done for QA purposes anyway. When it detects breakages, something like the algorithm above could be used to automatically find a solution as long as the portage, the ebuilds, and the packages themselves are not broken.

**Comment by edannenberg** [comment]
For anyone not following the Gentoo bug tracker, this was an issue with the `memcached` ebuild, already fixed but not yet with a stable keyword.

@berney Step 1 combined with `--pretend`, before installing at the host should do the trick. The rest might be a bit overkill, not sure yet. I should have a bit more time on my hands the coming days, will play around with the described process for a bit. Thanks for the suggestion!

**Comment by berney** [comment]
> @berney Step 1 combined with --pretend, before installing at the host, should do the trick.

I suspect that won't be enough, as it won't know until it has done a real emerge what the SONAMEs are. Once it's done that, portage will have the metadata in `/usr/portage/packages/Packages` regarding `PROVIDES` and `REQUIRES`. I don't think `--pretend` will generate these. If it does it will save a bunch of time. Should be easy to test to verify.

You're welcome. I'm happy to help. I really like your tool so thanks for sharing it.
